config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions
  resources :messages
  resources :conversations
  resources :friendships
root "sessions#index"
  get    '/login',   to: 'sessions#new', as: :login
  post   '/login',   to: 'sessions#create', as: nil
  delete '/logout',  to: 'sessions#destroy'

get '/auth/:provider/callback', :to => 'sessions#create'
get '/auth/failure', :to => 'sessions#failure'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  acts_as_readable on: :created_at
  is_impressionable
belongs_to :user, optional: true
  belongs_to :author, class_name: 'User'
belongs_to :receiver, class_name: 'User'
validates :author, uniqueness: {scope: :receiver}
has_many :messages, -> { order(created_at: :asc) }, dependent: :destroy
has_many :impressionists
scope :participating, -> (user) do
where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
end
def with(current_user)
author == current_user ? receiver : author
end
def participates?(user)
author == user || receiver == user
end
scope :between, -> (sender_id, receiver_id) do
where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :friend, :class_name => "User"
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :picture, PictureUploader
  acts_as_readable on: :created_at
   is_impressionable
  belongs_to :conversation
  belongs_to :user
  validates :body, presence: true
    has_many :impressionists
    def feed
     Message.where("user_id = ?", id)
   end
   def send_notifications!
        users = forum_thread.users.uniq - [user]
        users.each do |user|
            UserMailer.message_notification(user, self).deliver_later
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    acts_as_reader
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :messages, dependent: :destroy
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  def self.reader_scope
    where(is_admin: true)
  end
  def feed
    Message.where("user_id = ?", id)
  end
  def self.from_omniauth(auth_hash)
     user=find_or_create_by(uid: auth_hash['uid'],provider: auth_hash['provider'])
     user.name =auth_hash['info']['first_name']
     user.email =auth_hash['info']['email']
     user.password ='1234567'
     user.save!
     user
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include MessagesHelper
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, except: [:index]
before_action :check_participating!, except: [:index]
def index
  if(params[:user_id])
  @conversations = Conversation.participating(current_user).order('updated_at DESC')
else
@conversations=Conversation.all
end
end

def new
  redirect_to conversation_path(@conversation) and return if @conversation
  @message = current_user.messages.build
end
def show

  @receiver = User.find_by(id: params[:receiver_id])
@message = Message.new
  impressionist(@conversation)
end



private

def set_conversation
@conversation = Conversation.find_by(id: params[:id])
end
def check_participating!
  redirect_to conversations_path unless @conversation && @conversation.participates?(current_user)
end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friendships=Friendship.all
  end
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:success] = "Added friend."
      redirect_to conversations_path
    else
      flash[:error] = "Unable to add friend."
      redirect_to conversations_path
    end
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_conversation!, except: [:index]
  def index
    @messages=Message.all.order('updated_at DESC')
    @messages=current_user.messages.paginate(page: params[:page], :per_page => 10)
  end
def new
@message = current_user.messages.build
end

def show
  @message=Message.find(params[:id])
    impressionist(@message)
end

def create
  @receiver = User.find_by(id: params[:receiver_id])
  @conversation ||= Conversation.create(author_id: current_user.id,
                                        receiver_id: @receiver.id)
  @message = current_user.messages.build(message_params)
  @message.conversation_id = @conversation.id
  @message.save!
  if params[:receiver_id]
   UserMailer.welcome_email(@receiver).deliver_now
  flash[:success] = "Your message was sent!"
  redirect_to conversation_path(@conversation)
else
  flash[:success] = "Your message was sent!"
  redirect_to conversation_path(@conversation)
end
end

private

def message_params
  params.require(:message).permit(:body, :picture)
end
def find_conversation!
  if params[:receiver_id]
    @receiver = User.find_by(id: params[:receiver_id])
    redirect_to(conversations_path) and return unless @receiver
    @conversation = Conversation.between(current_user.id, @receiver.id)[0]
  else
    @conversation = Conversation.find_by(id: params[:conversation_id])
    redirect_to(conversations_path)  and return unless @conversation && @conversation.participates?(current_user)
  end
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
  def new
  end
  def show
  end
  def create
    if params[:session].present?
    user = User.find_by(email: params[:session][:email].downcase)
    #byebug
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to conversations_path
    else
      flash[:error] = 'Invalid email/password combination'
      render 'new'
    end
  else
    begin
      user=User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id]=user.id
      flash[:success]="Welcom, #{user.email}!"
    rescue
      flash[:warning]="Error!!"
    end
    redirect_to root_path
  end
end

  def destroy
    log_out
    redirect_to root_url
  end
  def failure
    render :text => "Sorry ,you not allow"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def new
    @user=User.new
  end

  def show
    @user=User.find(params[:id])
  end

  def create
    @user =User.new(user_params)
    if @user.save
      log_in @user
      flash[:success]="U created an account successfully!!"
      redirect_to conversations_path
    else
      flash[:error]="Fails!!"
      render 'new'
    end
  end

  def destroy

  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id]=user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  def current_user?(user)
    user== current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversation.html.erb
<% if  conversation.impressionist_count <=1 %>
<div>
  Chatting with <%= conversation.with(current_user).name %>
  <br>
  <em><%= conversation.messages.last.body.truncate(50) %></em>
  <br>
  <%= link_to "Create new message",conversation_path(conversation),class: 'btn btn-primary'%>
  <%= link_to "FriendList",friendships_path,class: 'btn btn-primary'%>
  <%= link_to "Sent Message", messages_path,class: 'btn btn-primary'%>
<% else %>
Chatting with <%= conversation.with(current_user).name %>
<br>
<em><%= conversation.messages.last.body.truncate(50) %></em>
<br>
<%= link_to "Create new message",conversation_path(conversation),class: 'btn btn-primary'%>
<%= link_to "FriendList",friendships_path,class: 'btn btn-primary'%>
<%= link_to "Sent Message", messages_path,class: 'btn btn-primary'%>
<% end %>

  <hr>
</div>

app/views/conversations/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a><%= link_to "Home",sessions_path%></a></li>
  <li class="breadcrumb-item active">Messages</li>
</ol>

<%if logged_in?%>
  <% if @conversations.count ==0%>
  <p>U dont have any conversations</p>
  <p> Find a user to add friend</p>
  <%=  link_to 'send a message', new_message_path(receiver_id: @user) %>
  <%else%>
  <div class="dropdown">
    <button onclick="myFunction()" class="dropbtn">Dropdown</button>
    <div id="myDropdown" class="dropdown-content">
      <% current_user.friendships.each do |friendship|%>
      <a><%=  link_to friendship.friend.name, new_message_path(receiver_id: friendship.friend) %></a>
      <%end%>
    </div>
  </div>
  <div class="main">
    <%= render @conversations %>
    <% end %>
  </div>

<%else%>
<h1 id="word">U havent login yet,Login to communicate with your friend</h1>
  <h2 id="word1"><%= link_to "Login", login_path, class: 'btn btn-primary custom',size: '30px' %></h2>
<%end%>

<% content_for :js do%>
<script type="text/javascript">
$(".card").hover(function() {
  $(this).addClass("conversation-highlight");
}, function(){
  $(this).removeClass("conversation-highlight");
});
$(document).ready(function(){
    $('.navbar .dropdown').hover(function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(250).slideDown();
    }, function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(100).slideUp()
    });
})
</script>

<%end%>

app/views/conversations/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a><%= link_to "Home",sessions_path%></a></li>
  <li class="breadcrumb-item "><%= link_to "Conversation",conversations_path%></li>
  <li class="breadcrumb-item active"><%= @conversation.with(current_user).name %></li>
</ol>
<h1>Chatting with <%= @conversation.with(current_user).name %></h1>

<div id="conversation-main">
  <div id="conversation-body">

    <%= render @conversation.messages %>
  </div>

  <%= form_for @message do |f| %>
    <%= hidden_field_tag 'conversation_id', @conversation.id %>
    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit %>
    <%= f.file_field :picture %>
  <% end %>
</div>
<% content_for :js do%>
<script type="text/javascript">
$(".message-thumbnail").hover(function() {
  $(this).addClass("conversation-highlight");
}, function(){
  $(this).removeClass("conversation-highlight");
});
</script>
<%end%>

app/views/friendships/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a><%= link_to "Home",sessions_path%></a></li>
  <li class="breadcrumb-item active">FriendList</li>
</ol>
<h1>FriendList</h1>
<%if logged_in?%>
<% if current_user.friendships.count ==0%>
<p>U dont have friend</p>
<p>Add some friend</p>
<%= link_to "Users", users_path%>
<% else %>
<% current_user.friendships.each do |friendship| %>
  <li>
    <%=  friendship.friend.name %>
    (<%= link_to "remove", friendship, :method => :delete %>)
      <%=  link_to 'send a message', new_message_path(receiver_id: friendship.friend) %>
  </li>
<% end %>
<p><%= link_to "Find Friends", users_path %></p>

</ul>
<%end%>
<%else%>
<h2><center>U haven't login yet</center></h2>
<h3><center>login to connect with the world</center></h3>
<center><%= link_to "Login",login_path,class: 'btn btn-primary'%></center>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FastMail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= yield :js %>
  </body>
</html>

app/views/messages/_message.html.erb
<% if message.mark_as_read! for: current_user %>
<div class="message-highlight">
<li highlight><%= truncate(message.body) %></li>
<p>at <strong><%= message.created_at %></strong><br>
  by <strong><%= message.user.name %></strong></p>
 <%= image_tag message.picture.url if message.picture? %> </br>
 <span class="timestamp">
  Posted <%= time_ago_in_words(message.created_at) %> ago.</br>
</span>
  </div>
<hr>
<% else%>
<li highlight><%= truncate(message.body) %></li>
<p>at <strong><%= message.created_at %></strong><br>
  by <strong><%= message.user.name %></strong></p>
 <%= image_tag message.picture.url if message.picture? %> </br>
 <span class="timestamp">
</span>
  Seen at <%=Time.current%>
<hr>
<% end %>

app/views/messages/index.html.erb
<h1>Messages</h1>

<%current_user.messages.each do |message|%>
<div class="card">
  <div class="card-body">
    <h4><%=message.body%></h4>
    <span class="timestamp">
      <%= image_tag message.picture.url if message.picture? %> </br>
     Posted <%= time_ago_in_words(message.created_at) %> ago.</br>
   </span>
  </div>
</div>
<%end%>
<%=will_paginate  @messages %>

app/views/messages/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a><%= link_to "Home",sessions_path%></a></li>
  <li class="breadcrumb-item active">Messages</li>
</ol>
<h1>New message to <%= @receiver.name %></h1>

<%= form_for @message do |f| %>
  <%= hidden_field_tag 'receiver_id', @receiver.id %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
  <%= f.file_field :picture %>
<% end %>

app/views/messages/show.html.erb
<%if  @message.impressionist_count ==0%>
<div class="message-highlight">
<div class="card">
  <div class="card-body">
    <%= @message.body %></li>
  <span class="view">View:<%= @message.impressionist_count %></br></span>
        <%= @message.read_by(current_user)%>
  <%=link_to "Back",conversations_path%>
  </div>
</div>
</div>
<% else %>

<div class="card">
  <div class="card-body">
    <%= @message.body %></li>
  <span class="view">View:<%= @message.impressionist_count %></br></span>
  <%=link_to "Back",conversations_path%>
  </div>
</div>

<%end%>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<p>U havent send an</p>
<% @users.each do |user|%>
<% if current_user.id==user.id %>
<div class="card">
  <div class="card-body">
    <p><%=user.name%>(You)</p>
  </div>
</div>
<% else %>
<div class="card">
  <div class="card-body">
    <p><%=user.name%></p> <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
  </div>
</div>
<%end%>
<% end %>

app/views/users/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a><%= link_to "Home",sessions_path%></a></li>
  <li class="breadcrumb-item active"><%=current_user.name%></li>
</ol>
<h1>Users</h1>
<ul><%= render "users/user" %></ul>

app/views/users/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a><%= link_to "Home",sessions_path%></a></li>
  <li class="breadcrumb-item active">Signup</li>
</ol>
<div class="row">
  <div class="col-md-6">
  <%= form_for (@user) do |f| %>
  <li>
    <%= f.label :name%>
    <%= f.text_field :name, class: 'form-control'%>
  </li>
  <li>
    <%= f.label :email%>
    <%= f.text_field :email, class: 'form-control'%>
  </li>
  <li>
    <%= f.label :password%>
    <%= f.password_field :password,class: 'form-control'%>
  </li>
  <li>
    <%= f.label :password%>
    <%= f.password_field :password,class: 'form-control'%>
    <%= f.submit "Create my account", class: 'btn btn-primary' %>
  </li>
  <%end%>
  </div>
</div>

app/views/users/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a><%= link_to "Home",sessions_path%></a></li>
  <li class="breadcrumb-item active"><%=current_user.name%></li>
</ol>
<h1>Hello</h1>
<h2>FriendList</h2>
<ul>
  <% for friendship in @user.friendships %>
    <li>
      <%=h friendship.friend.name %>
      (<%= link_to "remove", friendship, :method => :delete %>)
    </li>
  <% end %>
</ul>

<p><%= link_to "Find Friends", users_path %></p>

<h2>Friended by Users</h2>
<ul>
  <% for user in @user.inverse_friends %>
    <li><%=h user.name %></li>
  <% end %>
</ul>